### ISSUE TITLE
kernel-devel package is missing ./arch/arm/kernel/module.lds

### ISSUE THREAD

**Issue by speachy** [fedberry/kernel#26]
When trying to compile out-of-tree modules (eg via akmods or dkms) things go boom.  For example:

2019/02/05 09:21:45 akmodsbuild: ld -r  -EL -T ./scripts/module-common.lds -T ./
arch/arm/kernel/module.lds  --build-id  -o /tmp/akmodsbuild.Xahimsel/BUILD/wireg
uard-kmod-0.0.20181218/_kmod_build_4.19.12-1.rpi.fc29.armv7hl/src/wireguard.ko /
tmp/akmodsbuild.Xahimsel/BUILD/wireguard-kmod-0.0.20181218/_kmod_build_4.19.12-1
.rpi.fc29.armv7hl/src/wireguard.o /tmp/akmodsbuild.Xahimsel/BUILD/wireguard-kmod
-0.0.20181218/_kmod_build_4.19.12-1.rpi.fc29.armv7hl/src/wireguard.mod.o ;  true
2019/02/05 09:21:45 akmodsbuild: ld: cannot open linker script file ./arch/arm/kernel/module.lds: No such file or directory

This file needs to be included in the kernel-devel rpm...

**Comment by speachy** [comment]
See these similar reports for upstream Fedora kernels:

https://bugzilla.redhat.com/show_bug.cgi?id=1531182
https://bugzilla.redhat.com/show_bug.cgi?id=1574604

**Comment by speachy** [comment]
Oh, I forgot to mention, this is using the latest kernel available from fedberry Updates repo -- 

kernel-4.19.12-1.rpi.fc29.armv7hl

**Comment by agrez** [comment]
Thanks for the bug report @speachy. Should be an easy fix. I'll push up a new build soon.

**Comment by speachy** [comment]
FWIW, I believe this has been broken since Fedberry moved from 4.14 to 4.19 kernels.

And I wanted to thank you for your efforts in keeping Fedberry going.

**Comment by agrez** [comment]
Thanks @speachy. I've pushed a new kernel build into our 'testing' repo. It should hopefully fix the issue. Let me know if you still hit issues.

**Comment by speachy** [comment]
With 4.19.19-2.rpi.fc29.armv7hl, akmods successfully builds out-of-tree modules.  Thanks!

**Comment by agrez** [comment]
Good to hear! Closing the issue.
