### ISSUE TITLE
Bootloader entries are not being generated

### ISSUE THREAD

**Issue by r3pek** [fedberry/kernel#40]
Just installed the kernel on a rpi4 b running fc35. The /boot/loader/entries/ file isn't being generated after install.

**Comment by dwrobel** [comment]
This is not a kernel responsibility to generate those entries.

Please also be aware that this kernel does not use grub2 and this might be the reason why systemd-udev is not generating those entries.

**Comment by r3pek** [comment]
That might be it then... Was under the idea that installing the kernel on a "vanilla" FC35 would install all the needed bits to make it work. Ended up using one of the premade images that works great btw ;)

thx!

**Comment by dwrobel** [comment]
Pre-built images are essentially vanilla fedora + minimal list of changes to get the downstream kernel working.
